### ISSUE TITLE
大佬 发现换一个显示屏，图片就获取不全

### ISSUE THREAD

**Issue by cctyl** [wycm/selenium-geetest-crack#16]
（bilibili的验证码，同样用的是极验https://github.com/cctyl/SeleniumBiliLogin.git）
我在我自己的电脑上本来已经适配好了bilibili，但是
当我换一个电脑，屏幕大小改变时

`BufferedImage image = getImageEle(driver.findElement(By.cssSelector("canvas[class='geetest_canvas_bg geetest_absolute']")));
               `  
这里读取的图片就只能拿到一部分（bilibili的验证码）。可是我又没有办法使得每台电脑的屏幕大小都一样，特别是对于服务器，并没有屏幕，实际屏幕大小也不知道怎么定了。
大佬能指点一下吗

**Comment by zhouhuanghua** [comment]
滑动验证码的我还没试过，但是可以参考一下这样子：selenium调用js代码获取屏幕或者网页的分辨率，然后按比例截取，你看下这个思路有没有问题。




------------------ 原始邮件 ------------------
发件人: "cctyl"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 上午10:47
收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)




（bilibili的验证码，同样用的是极验https://github.com/cctyl/SeleniumBiliLogin.git）
 我在我自己的电脑上本来已经适配好了bilibili，但是
 当我换一个电脑，屏幕大小改变时
 
BufferedImage image = getImageEle(driver.findElement(By.cssSelector("canvas[class='geetest_canvas_bg geetest_absolute']"))); 
 这里读取的图片就只能拿到一部分（bilibili的验证码）。可是我又没有办法使得每台电脑的屏幕大小都一样，特别是对于服务器，并没有屏幕，实际屏幕大小也不知道怎么定了。
 大佬能指点一下吗

**Comment by cctyl** [comment]
大佬是这样子的，full.png截取没有问题。出问题在验证码的部分，即original.png 和slider.png，只获取到了图片上半部分，在对比rgb的地方就出错了
可是这两个图片是通过css选择器获取的，并没有实际的坐标，也就没有办法按比例获取。
且，按照截图方式，获取到的original.png和slider.png是一模一样的，就没有办法对比rgb了




------------------ 原始邮件 ------------------
发件人: "ThunderclapT丶"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 上午10:59
收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;
抄送: "我是空白"<2621460357@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)



滑动验证码的我还没试过，但是可以参考一下这样子：selenium调用js代码获取屏幕或者网页的分辨率，然后按比例截取，你看下这个思路有没有问题。 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "cctyl"<notifications@github.com>; 
 发送时间: 2019年7月23日(星期二) 上午10:47 
 收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16) 
 
 
 
 
 （bilibili的验证码，同样用的是极验https://github.com/cctyl/SeleniumBiliLogin.git） 
  我在我自己的电脑上本来已经适配好了bilibili，但是 
  当我换一个电脑，屏幕大小改变时 
   
 BufferedImage image = getImageEle(driver.findElement(By.cssSelector("canvas[class='geetest_canvas_bg geetest_absolute']")));  
  这里读取的图片就只能拿到一部分（bilibili的验证码）。可是我又没有办法使得每台电脑的屏幕大小都一样，特别是对于服务器，并没有屏幕，实际屏幕大小也不知道怎么定了。 
  大佬能指点一下吗

**Comment by zhouhuanghua** [comment]
抱歉，这个我研究的不深，没办法帮到你了




------------------ 原始邮件 ------------------
发件人: "cctyl"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 中午11:10
收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;
抄送: "782059973"<782059973@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)



大佬是这样子的，full.png截取没有问题。出问题在验证码的部分，即original.png 和slider.png，只获取到了图片上半部分，在对比rgb的地方就出错了 
 可是这两个图片是通过css选择器获取的，并没有实际的坐标，也就没有办法按比例获取。 
 且，按照截图方式，获取到的original.png和slider.png是一模一样的，就没有办法对比rgb了 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "ThunderclapT丶"<notifications@github.com>; 
 发送时间: 2019年7月23日(星期二) 上午10:59 
 收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>; 
 抄送: "我是空白"<2621460357@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16) 
 
 
 
 滑动验证码的我还没试过，但是可以参考一下这样子：selenium调用js代码获取屏幕或者网页的分辨率，然后按比例截取，你看下这个思路有没有问题。  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "cctyl"<notifications@github.com>;  
  发送时间: 2019年7月23日(星期二) 上午10:47  
  收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;  
  抄送: "Subscribed"<subscribed@noreply.github.com>;  
  主题: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)  
   
   
   
   
  （bilibili的验证码，同样用的是极验https://github.com/cctyl/SeleniumBiliLogin.git）  
   我在我自己的电脑上本来已经适配好了bilibili，但是  
   当我换一个电脑，屏幕大小改变时  
     
  BufferedImage image = getImageEle(driver.findElement(By.cssSelector("canvas[class='geetest_canvas_bg geetest_absolute']")));   
   这里读取的图片就只能拿到一部分（bilibili的验证码）。可是我又没有办法使得每台电脑的屏幕大小都一样，特别是对于服务器，并没有屏幕，实际屏幕大小也不知道怎么定了。  
   大佬能指点一下吗

**Comment by cctyl** [comment]
谢谢大佬了，我强行把窗口设置为我本地显示器大小（服务器没屏幕）
勉强解决了。
大佬以后要是有思路发在博客里


------------------ 原始邮件 ------------------
发件人: "ThunderclapT丶"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 中午11:13
收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;
抄送: "我是空白"<2621460357@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)



抱歉，这个我研究的不深，没办法帮到你了 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "cctyl"<notifications@github.com>; 
 发送时间: 2019年7月23日(星期二) 中午11:10 
 收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>; 
 抄送: "782059973"<782059973@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16) 
 
 
 
 大佬是这样子的，full.png截取没有问题。出问题在验证码的部分，即original.png 和slider.png，只获取到了图片上半部分，在对比rgb的地方就出错了  
  可是这两个图片是通过css选择器获取的，并没有实际的坐标，也就没有办法按比例获取。  
  且，按照截图方式，获取到的original.png和slider.png是一模一样的，就没有办法对比rgb了  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "ThunderclapT丶"<notifications@github.com>;  
  发送时间: 2019年7月23日(星期二) 上午10:59  
  收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;  
  抄送: "我是空白"<2621460357@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)  
   
   
   
  滑动验证码的我还没试过，但是可以参考一下这样子：selenium调用js代码获取屏幕或者网页的分辨率，然后按比例截取，你看下这个思路有没有问题。   
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "cctyl"<notifications@github.com>;   
   发送时间: 2019年7月23日(星期二) 上午10:47   
   收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;   
   抄送: "Subscribed"<subscribed@noreply.github.com>;   
   主题: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)   
     
     
     
     
   （bilibili的验证码，同样用的是极验https://github.com/cctyl/SeleniumBiliLogin.git）   
    我在我自己的电脑上本来已经适配好了bilibili，但是   
    当我换一个电脑，屏幕大小改变时   
       
   BufferedImage image = getImageEle(driver.findElement(By.cssSelector("canvas[class='geetest_canvas_bg geetest_absolute']")));    
    这里读取的图片就只能拿到一部分（bilibili的验证码）。可是我又没有办法使得每台电脑的屏幕大小都一样，特别是对于服务器，并没有屏幕，实际屏幕大小也不知道怎么定了。   
    大佬能指点一下吗

**Comment by zhouhuanghua** [comment]
好的




------------------ 原始邮件 ------------------
发件人: "cctyl"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 中午11:17
收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;
抄送: "782059973"<782059973@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)



谢谢大佬了，我强行把窗口设置为我本地显示器大小（服务器没屏幕） 
 勉强解决了。 
 大佬以后要是有思路发在博客里 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "ThunderclapT丶"<notifications@github.com>; 
 发送时间: 2019年7月23日(星期二) 中午11:13 
 收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>; 
 抄送: "我是空白"<2621460357@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16) 
 
 
 
 抱歉，这个我研究的不深，没办法帮到你了  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "cctyl"<notifications@github.com>;  
  发送时间: 2019年7月23日(星期二) 中午11:10  
  收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;  
  抄送: "782059973"<782059973@qq.com>;"Comment"<comment@noreply.github.com>;  
  主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)  
   
   
   
  大佬是这样子的，full.png截取没有问题。出问题在验证码的部分，即original.png 和slider.png，只获取到了图片上半部分，在对比rgb的地方就出错了   
   可是这两个图片是通过css选择器获取的，并没有实际的坐标，也就没有办法按比例获取。   
   且，按照截图方式，获取到的original.png和slider.png是一模一样的，就没有办法对比rgb了   
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "ThunderclapT丶"<notifications@github.com>;   
   发送时间: 2019年7月23日(星期二) 上午10:59   
   收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;   
   抄送: "我是空白"<2621460357@qq.com>;"Author"<author@noreply.github.com>;   
   主题: Re: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)   
     
     
     
   滑动验证码的我还没试过，但是可以参考一下这样子：selenium调用js代码获取屏幕或者网页的分辨率，然后按比例截取，你看下这个思路有没有问题。    
       
       
       
       
    ------------------ 原始邮件 ------------------    
    发件人: "cctyl"<notifications@github.com>;    
    发送时间: 2019年7月23日(星期二) 上午10:47    
    收件人: "wycm/selenium-geetest-crack"<selenium-geetest-crack@noreply.github.com>;    
    抄送: "Subscribed"<subscribed@noreply.github.com>;    
    主题: [wycm/selenium-geetest-crack] 大佬 发现换一个显示屏，图片就获取不全 (#16)    
       
       
       
       
    （bilibili的验证码，同样用的是极验https://github.com/cctyl/SeleniumBiliLogin.git）    
     我在我自己的电脑上本来已经适配好了bilibili，但是    
     当我换一个电脑，屏幕大小改变时    
         
    BufferedImage image = getImageEle(driver.findElement(By.cssSelector("canvas[class='geetest_canvas_bg geetest_absolute']")));     
     这里读取的图片就只能拿到一部分（bilibili的验证码）。可是我又没有办法使得每台电脑的屏幕大小都一样，特别是对于服务器，并没有屏幕，实际屏幕大小也不知道怎么定了。    
     大佬能指点一下吗
