### ISSUE TITLE
现在换了验证方式，不是切割图片了，怎么验证缺口位置？

### ISSUE THREAD

**Issue by devilishes** [wycm/selenium-geetest-crack#4]
def get_offset(self):
        # 比较两个像素点
        def match(i1, i2, t):
            p1 = [int(p) for p in i1]
            p2 = [int(p) for p in i2]
            if abs(p1[0] - p2[0]) < t and abs(p1[1] - p2[1]) < t and abs(p1[2] - p2[2]) < t:
                return True
            return False
        offset = -1
        img1 = cv2.imread(ig1)
        img2 = cv2.imread(ig2)

        for j in range(260):
            for i in range(160):
                if not match(img1[i][j], img2[i][j], self.threshold):
                    offset = j
                    return offset
        return offset

ig1是有缺口的，ig2是完整的
这样好像实现获取不了偏移量
请教大师

**Comment by wycm** [comment]
分别求差绝对值之和再比较

**Comment by wycm** [comment]
页面结构略有改动，feature_20180904_hotfix分支修复，但是原来的移动算法又失效了。
移动轨迹算法还在探索中....

**Comment by devilishes** [comment]
大神，有qq么，++一下，讨教学习一下

在 2018-09-06 10:30:01，"wycm" <notifications@github.com> 写道：


页面结构略有改动，feature_20180904_hotfix分支修复，但是原来的移动算法又失效了。
移动轨迹算法还在探索中....

**Comment by wycm** [comment]
1057160387
